### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by WoWEye** [matthewhively/MageButtons#3]
Will you be posting this on either WowInterface or curseforge so download managers can find it? Like Wowinterface or Curseforge?

**Comment by matthewhively** [comment]
@WoWEye 
I could, but it would have to be under a different name than the ones that already exist on those sites.
Ideally the original author would have to upload a new version from this repo to his addon on wowinterface.
Unfortunately he is MIA most of the time, so not a huge likelihood of that happening in the short term.
The good news is, since there isn't much development work happening on this mod, the utility of download managers to "keep it up to date" is modest at best. So you can download it, install it, and forget about it for the most part.

There MIGHT be a way to set your download manager to look at this repo directly for this specific addon. I'm not sure about that though.

**Comment by WoWEye** [comment]
Im using WowUp. when I try to install by URL using the 'copy' button on the Code page i get this error.
No asset was found to download from https://githum.com/matthwhively/MageButtons.git
A valid zip file with  '-bc' is required in order for WowUp to download it.

When I try copying the path from Code > download zip I get the folder  MageButtons-main.zip. Which of course the -main messes it up.

I will sit here patiently hoping for something  ;-)

**Comment by matthewhively** [comment]
@WoWEye 
I'm gonna take a quick stab at getting you a direct zip file you can import into wowup.
If that fails, I'll try something else.

**Comment by matthewhively** [comment]
I created a new release v1.05
https://github.com/matthewhively/MageButtons/releases/tag/v1.05
Uploaded zip files.
See if you can get wowup to work with this.

**Comment by WoWEye** [comment]
It's getting closer. When I put in the url I get the option to Import, then Install, but it hangs on the  install.I do appreciate your time /effort in getting this to work.

Family and Honour first 

    On Thursday, January 27, 2022, 01:56:23 a.m. MST, Matthew Hively ***@***.***> wrote:  
 
 


I created a new release v1.05
https://github.com/matthewhively/MageButtons/releases/tag/v1.05
Uploaded zip files.
See if you can get wowup to work with this.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by matthewhively** [comment]
I tried it myself last night, and I saw the same "hang" at first.
I ended up restarting wowup, and pasted the exact link to the 1.05 release (not to the zip file directly) and it worked for me.
Try that.

**Comment by WoWEye** [comment]
OHH YES!! it worked, Thanks So Much

Family and Honour first 

    On Thursday, January 27, 2022, 12:14:20 p.m. MST, Matthew Hively ***@***.***> wrote:  
 
 


I tried it myself last night, and I saw the same "hang" at first.
I ended up restarting wowup, and pasted the exact link to the 1.05 release (not to the zip file directly) and it worked for me.
Try that.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
